//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrianglesDiffColor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrianglesDiffColor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;x1&quot;: 90,
        ///		&quot;y1&quot;: 30,
        ///		&quot;x2&quot;: 90,
        ///		&quot;y2&quot;: 40,
        ///		&quot;x3&quot;: 80,
        ///		&quot;y3&quot;: 40
        ///	},
        ///	{
        ///		&quot;x1&quot;: 150,
        ///		&quot;y1&quot;: 130,
        ///		&quot;x2&quot;: 0,
        ///		&quot;y2&quot;: 90,
        ///		&quot;x3&quot;: 100,
        ///		&quot;y3&quot;: 0
        ///	},
        ///	{
        ///		&quot;x1&quot;: 20,
        ///		&quot;y1&quot;: 80,
        ///		&quot;x2&quot;: 80,
        ///		&quot;y2&quot;: 70,
        ///		&quot;x3&quot;: 50,
        ///		&quot;y3&quot;: 100
        ///	},
        ///	{
        ///		&quot;x1&quot;: 60,
        ///		&quot;y1&quot;: 100,
        ///		&quot;x2&quot;: 120,
        ///		&quot;y2&quot;: 80,
        ///		&quot;x3&quot;: 140,
        ///		&quot;y3&quot;: 120
        ///	},
        ///	{
        ///		&quot;x1&quot;: 100,
        ///		&quot;y1&quot;: 100,
        ///		&quot;x2&quot;: 120,
        ///		&quot;y2&quot;: 100,
        ///		&quot;x3&quot;: 120,
        ///		&quot;y3&quot;: 90
        ///	},
        ///	{
        ///		&quot;x1&quot;: 30,
        ///		&quot;y1&quot;: 70,
        ///		&quot;x2&quot;: 100,
        ///		&quot;y2&quot;: 10,
        ///		&quot;x3&quot;: 110 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Coordinates {
            get {
                return ResourceManager.GetString("Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;x1&quot;: 170,
        ///		&quot;y1&quot;: 120,
        ///		&quot;x2&quot;: 90,
        ///		&quot;y2&quot;: 40,
        ///		&quot;x3&quot;: 80,
        ///		&quot;y3&quot;: 40
        ///	},
        ///	{
        ///		&quot;x1&quot;: 150,
        ///		&quot;y1&quot;: 130,
        ///		&quot;x2&quot;: 0,
        ///		&quot;y2&quot;: 90,
        ///		&quot;x3&quot;: 100,
        ///		&quot;y3&quot;: 0
        ///	}
        ///].
        /// </summary>
        public static string TestCoordinates {
            get {
                return ResourceManager.GetString("TestCoordinates", resourceCulture);
            }
        }
    }
}
